### ISSUE TITLE
Issue with make, and Error 127

### ISSUE THREAD

**Issue by Z035** [Arksine/katapult#105]
When I run `make`, the error pop up:
```
phoebus@035:~/Documents/github/katapult$ make
  Creating symbolic link out/board
  Building out/autoconf.h
  Compiling out/src/sched.o
make: arm-none-eabi-gcc: No such file or directory
make: *** [Makefile:71: out/src/sched.o] Error 127
```
I tried to resolve the problem by first `make clean` then `make`. But the problem persists

**Comment by Arksine** [comment]
You don't have the build tools installed correctly.   Katapult is derived from [Klipper](https://github.com/Klipper3d/klipper), so if  you have Klipper installed on your machine you should be able to build Katapult.
