### ISSUE TITLE
EBB SB2209 CAN RP2040 - No RP2040 Option in Katapult Configuration

### ISSUE THREAD

**Issue by TimGehres** [Arksine/katapult#99]
I ran the following but the Katapult Configuration doesn't list the Raspberry Pi RP2040 option, it only  lists LPC1786 options. 

Am I missing something, like not getting the correct git files? 

I copied and ran this out of **https://github.com/Arksine/katapult** website.

  git clone https://github.com/Arksine/katapult
  cd katapult
  make menuconfig
 
Here is a screenshot of the Configuration menu that I get when running make menuconfig
****
<img width="506" alt="No RP2040" src="https://github.com/Arksine/katapult/assets/128931820/eb36be21-82ff-47b9-8177-0e60fa997203">

So, this is what it should look like:

The BIGTREETECH documentation for the EBB SB2209 CAN RP2040 pictures the following. (I **realize** the new menuconfig is now Katapult and not CanBoot)

<img width="603" alt="BTT RP2209" src="https://github.com/Arksine/katapult/assets/128931820/fe66642a-83bd-4eb2-9483-bd8bc9872bb9">

**Comment by Arksine** [comment]
The first screenshot is the default initial configuration.  You have to select the RP2040 within the `Micro-controller Architecture` sub-menu.

**Comment by TimGehres** [comment]
Hi Eric,

Thanks for getting back with me and pointing me in the right direction. I thought it would be something simple. I appreciate your help

Thanks again,
Tim

**Comment by Arksine** [comment]
You're welcome.  I'll go ahead and close this, hope that the build/upload goes smoothly.
